# Generated by Django 3.2.12 on 2025-05-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam_app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepage',
            name='name_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='imagepage',
            name='name_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
