# Generated by Django 3.2.12 on 2025-05-26 12:47

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cam_app2', '0002_auto_20250526_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepage',
            name='instructions',
            field=wagtail.core.fields.RichTextField(blank=True, default='<p>Select one or more images and click Upload &amp; Run below.</p>'),
        ),
        migrations.AddField(
            model_name='imagepage',
            name='run_label',
            field=models.CharField(default='Upload & Run', max_length=50),
        ),
        migrations.AddField(
            model_name='imagepage',
            name='upload_label',
            field=models.CharField(default='Choose Files', max_length=50),
        ),
    ]
