# Generated by Django 3.2.12 on 2025-05-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cam_app2', '0003_auto_20250526_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepage',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='imagepage',
            name='run_label',
        ),
        migrations.RemoveField(
            model_name='imagepage',
            name='upload_label',
        ),
    ]
